server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/cloudserverclientservice01/
  profiles:
    active: native, dev, prod, sit
