example.property: I AM THE SIT
spring.jpa.database: postgresql
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.platform: postgresql
spring.datasource.url: jdbc:postgresql://localhost:5432/eagle_eye_local
spring.datasource.name: postgres
spring.datasource.username: postgres
spring.datasource.password: admin
spring.datasource.dbcp2.test-while-idle: true
spring.datasource.dbcp2.validation-query: SELECT 1
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.devtools.add-properties: false
